### ISSUE TITLE
app doesnt start up after update

### ISSUE THREAD

**Issue by t4nd0** [SecUSo/privacy-friendly-notes#108]
hey since the last update to version 1.1.1 the pfa app doesnt start on my pixel 5 anymore.  any way to fix this or secure the notes? please i have a lot of notes

**Comment by t4nd0** [comment]
fixed the problem with a forced downgrade through adb

**Comment by Kamuno** [comment]
Can you send us the Crash Stack trace?

**Comment by DanielRieken** [comment]
Same Problem here. Since last upate to version 1.1.1 the app doens't start anymore. When I delete the "allthenotes" file, the app starts again, but of course I don't want to delete this file...

**Comment by Kamuno** [comment]
F-Droid is sadly rather slow in pushing the update.. we have released v1.2.3 by now. I hope that f-droid will publish the update fast.

To secure your Notes you should be able to use the Backup Application here: https://github.com/SecUSo/privacy-friendly-backup/releases/tag/v1.3

The Backup Application is also available on F-Droid but it was just recently released and it will only work with the Notes App from v1.2.0 on

So will either have to use the version from GitHub or the version from the Google PlayStore if you want to backup your data now. If you can wait a bit for F-Droid to catch up you can use the latest Note Version with the Backup App from F-Droid.

**Comment by DanielRieken** [comment]
Installed 1.2.3 and the app is still crashing.
Installed PFB 1.3 which was able to backup the data vom PFN. Then reset PFN so it successfully starts again.
Restored backup with PFB and then PFN crashes again.
Finally installed the good old Note Everything app (SoftXperience) I've been using for years before PFN.
Opened the "allthenotes.db" with DB Browser for SQLite on Windows and copy&pasted all the notes from PFN to Note Everything.
Thanks anyway for developing PFx...

**Comment by pnielsenz** [comment]
I have this same problem. The actual note database in previous versions seems to be stored at /data/data/org.secuso.privacyfriendlynotes/databases/ in the two files allthenotes and allthenotes-journal, and I was able to migrate from one phone to another by copying these two files using Amaze with rooted phones.

The backup program doesn't seem to work with older versions of PFN, which makes it pretty useless, to transfer notes to the new version. I'd love to be corrected if this is incorrect, and get instructions for doing a backup and restore to the new version.

**Comment by J-oe-rg** [comment]
I have the same issue. I updated from v1.0.2 with about 40 notes in it. I have no idea if versions v1.1.x from mid of July were usable. But v1.2.3 to v1.2.5 from beginning of August crash immediately after start.
I did a backup with "Privacy Friendly Backup" (PFB) about nine days ago with v1.2.3. The backup can be exported and it is readable within a text editor (but it is a pain).
I installed v1.2.5 on a second Android device. It is completely useable. But as soon I import above backup on my second device with help of PFB the app crashes here too.
Yesterday I installed F-Droid on my second device to downgrade to an older version of PFN bot all versions smaller than v1.2.3 disappeared at last weekend. But probably this will not help anyhow. Before installing a different version the old one needs to be deinstalled and this will also delete the database. My devices are not rooted so I cannot reach / save the DB files directly.

@Kamuno: Above you asked for a stack trace. Here is mine from my first device with the original database. There I never tried an import. The program complains about database schema. Some columns have a different order and some of "my" fields (e.g. _id) allow NULL.

> 2022-08-15 12:02:31.792 1400-2418/? E/ActivityTrigger: activityStartTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.SplashActivity/11
2022-08-15 12:02:31.792 1400-2418/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.SplashActivity/11
2022-08-15 12:02:31.799 1400-2550/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.SplashActivity/11
2022-08-15 12:02:31.901 1400-3677/? E/ActivityTrigger: activityStartTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.main.MainActivity/11
2022-08-15 12:02:31.902 1400-3677/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.main.MainActivity/11
2022-08-15 12:02:31.915 1400-2550/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.main.MainActivity/11
2022-08-15 12:02:32.017 29608-29636/? E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
    Process: org.secuso.privacyfriendlynotes, PID: 29608
    java.lang.RuntimeException: Exception while computing database live data.
        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Pre-packaged database has an invalid schema: notes(org.secuso.privacyfriendlynotes.room.model.Note).
     Expected:
    TableInfo{name='notes', columns={name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, _id=Column{name='_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, in_trash=Column{name='in_trash', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, type=Column{name='type', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, category=Column{name='category', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, content=Column{name='content', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
     Found:
    TableInfo{name='notes', columns={in_trash=Column{name='in_trash', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='0'}, name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, _id=Column{name='_id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1, defaultValue='null'}, type=Column{name='type', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, category=Column{name='category', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0, defaultValue='null'}, content=Column{name='content', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:163)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:201)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:526)
        at androidx.room.util.DBUtil.query(DBUtil.java:86)
        at org.secuso.privacyfriendlynotes.room.dao.NoteDao_Impl$6.call(NoteDao_Impl.java:249)
        at org.secuso.privacyfriendlynotes.room.dao.NoteDao_Impl$6.call(NoteDao_Impl.java:246)
        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
        	... 3 more
2022-08-15 12:02:32.043 1400-2110/? E/InputDispatcher: channel '78db74 org.secuso.privacyfriendlynotes/org.secuso.privacyfriendlynotes.ui.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

I hope this will help to identify the issue.

**Comment by Kamuno** [comment]
Should be fixed in the next version by #114 and #115

**Comment by J-oe-rg** [comment]
> > The backup program doesn't seem to work with older versions of PFN, which makes it pretty useless, to transfer notes to the new version. I'd love to be corrected if this is incorrect, and get instructions for doing a backup and restore to the new version.
> 
> Actually Notes was the first App integrated into the Backup App.. it also works with version 1.0.2
> 
> @J-oe-rg : can you try importing a backup but change the database Version from 3 to 1 in the backup file? It should look something like this in the backup file (unencrypted): `(..."{\"database\":{\"version\":1,\"content\"...)`

Version 1 did not help but your response made me playing arround with my backup file again. It contains also a lot of notes that are marked for deletion (in_trash equal to 1). I deleted some and the import worked. Finally I identified the first deleted note as the root cause:
`{\"_id\":1,\"type\":1,\"name\":\"Überschrift\",\"content\":\"Die Notiz\",\"category\":null,\"in_trash\":1}`

While I'm writing this I received your message regarding #114 which is telling me I was on the right track.

PS: I was just testing on my second device. I will not touch the first one with the original ('corrupt') database. There I will wait for the next version. Then I can test if it can correct an existing 'corrupt' database and on the second device the import of a 'corrupt' backup. ;-)

**Comment by Kamuno** [comment]
Ah, perfect. As I can see the category was null in this entry.. this is exactly what we just fixed.

Just to make sure.. are you using the Backup-App from F-Droid? Because The Backup App in F-Droid was not released yet so it will only work with the GitHub or PlayStore version of the Backup App.

**Comment by Kamuno** [comment]
So the new version was just released. I closed the issue for now but please just reopen it if the problem comes up again.

**Comment by J-oe-rg** [comment]
I updated from v1.2.5 to v1.3.0 today on my first device and it works perfect! Now it can read the original 'corrupt' database. 

On my second device I deinstalled v1.2.5 and installed v1.3.0 and imported the original backup from my first device with the null-category in it. I used Privacy Friendly Backup 1.3 from Google Playstore. Also here latest PFN v1.3.0 works fine now!
Thank you very much!

**Comment by DanielRieken** [comment]
> Thank you very much!
so it took 18 days to fix this bug? awesome
